openapi: 3.1.0
info:
  title: Optima Solutions - Asteo Ticketing
  description: Remote API to interact between Freshdesk accounts and MasMovil application.
  version: 1.0.0

servers:
  - url: 'https://asteo.pre.optimaprivatecloud.es'
    description: Staging Server
  - url: 'https://asteo.optimaprivatecloud.es'
    description: Production Server

security:
  - basicAuth: []

paths:
  /troubleTicket:
    post:
      summary: Create a new ticket in TO.
      description: Create a new ticket in the Freshdesk instance that corresponds depending on the requested data.
      tags:
        - fromTUtoTO
      requestBody:
        description: Ticket attributes needed to create a new ticket.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ticket'
            examples:
              asteo:
                $ref: '#/components/examples/ticketCreateAsteo'
              redaberta:
                $ref: '#/components/examples/ticketCreateRedAberta'
              fictional:
                $ref: '#/components/examples/ticketCreateFictional'
      responses:
        "201":
          $ref: '#/components/responses/ticketCreated'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
  /troubleTicket/{primaryKey}:
    patch:
      summary: Update an existing ticket from TU to TO.
      description: Update the ticket in TO system.
      tags:
        - fromTUtoTO
      parameters: 
        - in: path
          name: primaryKey
          required: true
          schema:
            type: string
            description: Primary key of the ticket.
      requestBody:
        description: Ticket object to update a ticket.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateTicket'
            examples:
              tuRejectCancellation:
                $ref: '#/components/examples/tuRejectCancellation'
              tuRejectResolution:
                $ref: '#/components/examples/tuRejectResolution'
              tuSendInformation:
                $ref: '#/components/examples/tuSendInformation'
              tuClose:
                $ref: '#/components/examples/tuClose'
              tuSendInformationNoChangeStatus:
                $ref: '#/components/examples/tuSendInformationNoChangeStatus'
              tuCancel:
                $ref: '#/components/examples/tuCancel'
      responses:
        "200":
          $ref: '#/components/responses/ticketUpdated'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
  /troubleTicket/update:
    post:
      summary: Update an existing ticket from TO to TU.
      description: The ticket status changes in TO and send information to TU.
      tags:
        - fromTOtoTU
      requestBody:
        description: Ticket object to update a ticket.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateTicket'
            examples:
              toRequestInformation:
                $ref: '#/components/examples/toRequestInformation'
              toRequestCancelation:
                $ref: '#/components/examples/toRequestCancelation'
              toResolve:
                $ref: '#/components/examples/toResolve'
      responses:
        "200":
          $ref: '#/components/responses/ticketUpdated'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    unauthorized:
      description: Unauthorized
    badRequest:
      description: Bad request. An error occurred when send request.
      content:
        application/json:
          schema:
            oneOf:
              - $ref: "#/components/schemas/illegalArgumentException"
              - $ref: "#/components/schemas/remoteException"
          examples:
            illegalArgumentException:
              $ref: '#/components/examples/illegalArgumentException'
            remoteException:
              $ref: '#/components/examples/remoteException'
    ticketCreated:
      description: The ticket has been created successfully.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ticketKeys"
    ticketUpdated:
      description: The ticket has been updated successfully.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/updateTicket"
  schemas:
    ticketId:
      type: object
      properties:
        mirrorKey: 
          type: string
          examples:
            - AS-5000
    ticketPrimaryKey:
      type: object
      properties:
        primaryKey:
          type: string
          description: Primary key from TO system.
          examples:
            - AS-18
    ticketKeys:
      allOf:
        - $ref: "#/components/schemas/ticketId"
        - $ref: "#/components/schemas/ticketPrimaryKey"
    ticketBase:
      type: object
      properties:
        dialog:
          type: string
        troubleType:
          type: string
        troubleDescription:
          type: string
        preferredPriority:
          type: integer
        customerTroubleNum: 
          type: string
        wh1Parameter: 
          type: string
    ticket:
      allOf:
        - $ref: "#/components/schemas/ticketId"
        - $ref: "#/components/schemas/ticketBase"
        - type: object
          properties:
            baseTroubleTicketState :
              type: string
            troubleDetectionTime:
              type: string
              format: date-time
              description: Issue dectention datetime.
            troubledObject:
              type: string
            homeID:
              type: string
              description: Client home identifier. This field is required when issue type is client and IUA is not ready.
              maxLength: 255
            wh2Parameter:
              type: string
              description: Additional information.
              maxLength: 255
            wh3Parameter:
              type: string
              description: Additional information.
              maxLength: 255
            wh4Parameter:
              type: string
              description: Additional information.
              maxLength: 255
            wh5Parameter:
              type: string
              description: Additional information.
              maxLength: 255
            customer: 
              type: string
            attachments:
              type: array
              items:
                type: object
                description: An attachment.
                properties:
                  content:
                    type: string
                    description: The actual contents of the attachment object, if embedded, encoded as base64.
                  mimeType:
                    type: string
                    description: Attachment mime type such as extension file for video, picture and document.
                  name: 
                    type: string
                    description: The name of the attachment.
    updateTicket:
      allOf:
        - $ref: "#/components/schemas/ticketKeys"
        - $ref: "#/components/schemas/ticketBase"
    illegalArgumentException:
      type: object
      description: Exception for wrong value if any of the fields of the received ticket has an invalid value, a required field is missing, etc.
      properties:
        illegalArgumentException:
          type: string
    remoteException:
      type: object
      description: Exception of the real TT system; communication errors with the same, etc.
      properties:
        remoteException:
          type: string
  examples:
    ticketCreateAsteo:
      summary: Create a ticket in Asteo FD instance
      value:
        baseTroubleTicketState: OPENACTIVE
        mirrorKey: AS-5000
        customerTroubleNum: O06999999999
        dialog: Ticket from API
        troubleType: Question
        troubleDescription: This the detailed information.
        troubleDetectionTime: '2023-07-20T00:00:00'
        preferredPriority: 1
        troubledObject: Afected
        clearancePerson: Remote Agent
        homeID: '01234'
        gescal37ID: Gescal37
        wh1Parameter: Red
        wh2Parameter: Additional information
        wh3Parameter: Additional information
        wh4Parameter: Additional information
        wh5Parameter: Additional information
        customer: 10
        attachments:
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file1.txt
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file2.txt
    ticketCreateRedAberta:
      summary: Create a ticket in Red Aberta FD instance
      value:
        baseTroubleTicketState: OPENACTIVE
        mirrorKey: RED-5001
        customerTroubleNum: O15999999999
        dialog: Ticket from API
        troubleType: Question
        troubleDescription: This the detailed information.
        troubleDetectionTime: '2023-07-20T00:00:00'
        preferredPriority: 1
        troubledObject: Afected
        clearancePerson: Remote Agent
        homeID: '01234'
        gescal37ID: Gescal37
        wh1Parameter: Red
        wh2Parameter: Additional information
        wh3Parameter: Additional information
        wh4Parameter: Additional information
        wh5Parameter: Additional information
        customer: 10
        attachments:
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file1.txt
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file2.txt
    ticketCreateFictional:
      summary: Create a ticket from Fictional IUA
      value:
        baseTroubleTicketState: OPENACTIVE
        mirrorKey: RED-5001
        customerTroubleNum: X99999999999
        dialog: Ticket from API
        troubleType: Question
        troubleDescription: This the detailed information.
        troubleDetectionTime: '2023-07-20T00:00:00'
        preferredPriority: 1
        troubledObject: Afected
        clearancePerson: Remote Agent
        homeID: 'XAS88840049000000000000000000000000772'
        gescal37ID: Gescal37
        wh1Parameter: Red
        wh2Parameter: Additional information
        wh3Parameter: Additional information
        wh4Parameter: Additional information
        wh5Parameter: Additional information
        customer: 10
    tuRejectCancellation:
      summary: TU rejects cancellation request
      value:
        baseTroubleTicketState: OPENACTIVE
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: This will be inserted as a Note in FD.
        clearancePerson: Remote Agent
    tuRejectResolution:
      summary: TU rejects ticket resolution
      value:
        baseTroubleTicketState: OPENACTIVE
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: Write here the detailed information about the reject ticket resolution.
    tuSendInformation:
      summary: TU send additional information
      value:
        baseTroubleTicketState: OPENACTIVE
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: Write here iformation about the files.
        attachments:
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file1.txt
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file2.txt
    tuClose:
      summary: TU close the ticket
      value:
        baseTroubleTicketState: CLOSED
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: The ticket was closed.
    tuSendInformationNoChangeStatus:
      summary: TU send additional information without status change
      value:
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: Write here iformation about the files.
        attachments:
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file1.txt
          - content: "ZmlsZSBudW1iZXIgMQ=="
            mimeType: text/plain
            name: file2.txt
    tuCancel:
      summary: TU cancel the ticket
      value:
        baseTroubleTicketState: CLOSED.CANCELED
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: The ticket was canceled.
    toRequestInformation:
      summary: TO request additional information
      value:
        baseTroubleTicketState: DEFERRED.AWAITING-INFORMATION
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: We need more information.
    toRequestCancelation:
      summary: TO request cancelation
      value:
        baseTroubleTicketState: DEFERRED.AWAITING-CANCELATION
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: We want to cancel the ticket.
    toResolve:
      summary: TO resolve the ticket
      value:
        baseTroubleTicketState: CLEARED
        primaryKey: AS-13
        mirrorKey: RED-5001
        dialog: We resolved the ticket.
    illegalArgumentException:
      summary: Validation error
      value:
        illegalArgumentException: 'Required fields: mirrorKey, baseTroubleTicketState'
    remoteException:
      summary: Save error
      value:
        remoteException: 'Could not save the entity: any reason'